/**
 * Seed data: Top 50 common Indian packaged food products
 * Each product includes barcode, name, brand, ingredients, and nutritional info per 100g.
 * Data sourced from product labels and Open Food Facts.
 */

const seedProducts = [
  // ── Biscuits & Snacks ──
  {
    barcode: '8901063010116',
    name: 'Parle-G Gold Biscuits',
    brand: 'Parle',
    category: 'biscuits',
    ingredients_text: 'Wheat Flour (Maida), Sugar, Edible Vegetable Oil (Palm Oil), Invert Syrup, Leavening Agents (INS 503, INS 500), Milk Solids, Salt, Emulsifier (INS 322), Dough Conditioner (INS 223)',
    sugar_100g: 26.7,
    salt_100g: 0.6,
    saturated_fat_100g: 8.5,
    image_url: null,
  },
  {
    barcode: '8901063010109',
    name: 'Parle-G Original Glucose Biscuits',
    brand: 'Parle',
    category: 'biscuits',
    ingredients_text: 'Wheat Flour (Maida), Sugar, Edible Vegetable Oil (Palm Oil), Invert Syrup, Leavening Agents (INS 503, INS 500), Milk Solids, Salt, Emulsifier (INS 322)',
    sugar_100g: 25.0,
    salt_100g: 0.5,
    saturated_fat_100g: 7.0,
    image_url: null,
  },
  {
    barcode: '8901063041325',
    name: 'Hide & Seek Chocolate Chip Cookies',
    brand: 'Parle',
    category: 'biscuits',
    ingredients_text: 'Wheat Flour (Maida), Sugar, Edible Vegetable Oil (Palm Oil), Choco Chips (Sugar, Cocoa Solids, Cocoa Butter, Emulsifier INS 322), Invert Syrup, Cocoa Solids, Leavening Agents (INS 500, INS 503), Butter, Salt, Milk Solids, Emulsifier (INS 322), Artificial Flavour',
    sugar_100g: 30.0,
    salt_100g: 0.5,
    saturated_fat_100g: 12.0,
    image_url: null,
  },
  {
    barcode: '8901063036253',
    name: 'Monaco Classic Salted Biscuits',
    brand: 'Parle',
    category: 'biscuits',
    ingredients_text: 'Wheat Flour (Maida), Edible Vegetable Oil (Palm Oil), Sugar, Yeast, Salt, Baking Powder (INS 500), Malt Extract, Milk Solids, Emulsifier (INS 322)',
    sugar_100g: 5.0,
    salt_100g: 2.0,
    saturated_fat_100g: 9.0,
    image_url: null,
  },
  {
    barcode: '8901063017207',
    name: 'Britannia Good Day Butter Cookies',
    brand: 'Britannia',
    category: 'biscuits',
    ingredients_text: 'Wheat Flour (Maida), Sugar, Edible Vegetable Oil (Palm Oil), Butter, Invert Syrup, Leavening Agents (INS 503, INS 500), Milk Solids, Salt, Emulsifier (INS 322), Artificial Flavour',
    sugar_100g: 24.0,
    salt_100g: 0.4,
    saturated_fat_100g: 11.0,
    image_url: null,
  },
  {
    barcode: '8901063002005',
    name: 'Britannia Marie Gold Biscuits',
    brand: 'Britannia',
    category: 'biscuits',
    ingredients_text: 'Wheat Flour (Maida), Sugar, Edible Vegetable Oil (Palm Oil), Invert Syrup, Leavening Agents (INS 503, INS 500), Milk Solids, Salt, Emulsifier (INS 322)',
    sugar_100g: 22.0,
    salt_100g: 0.5,
    saturated_fat_100g: 6.5,
    image_url: null,
  },
  {
    barcode: '8901063026100',
    name: 'Britannia 50-50 Maska Chaska',
    brand: 'Britannia',
    category: 'biscuits',
    ingredients_text: 'Wheat Flour (Maida), Edible Vegetable Oil (Palm Oil), Sugar, Spice Mix, Salt, Leavening Agents (INS 503, INS 500), Butter, Yeast, Emulsifier (INS 322), Onion Powder, Garlic Powder',
    sugar_100g: 8.0,
    salt_100g: 1.8,
    saturated_fat_100g: 9.5,
    image_url: null,
  },
  {
    barcode: '8901058008203',
    name: 'Britannia NutriChoice Digestive Biscuits',
    brand: 'Britannia',
    category: 'biscuits',
    ingredients_text: 'Whole Wheat Flour (Atta), Edible Vegetable Oil (Palm Oil), Sugar, Wheat Bran, Oats, Leavening Agents (INS 500, INS 503), Salt, Emulsifier (INS 322), Malt Extract',
    sugar_100g: 16.0,
    salt_100g: 0.8,
    saturated_fat_100g: 7.0,
    image_url: null,
  },
  {
    barcode: '8901030310805',
    name: 'Sunfeast Dark Fantasy Choco Fills',
    brand: 'ITC Sunfeast',
    category: 'biscuits',
    ingredients_text: 'Wheat Flour (Maida), Sugar, Edible Vegetable Oil (Palm Oil), Choco Cream (Sugar, Cocoa Powder, Vegetable Fat, Emulsifier INS 322, Flavour), Cocoa Powder, Invert Syrup, Leavening Agents (INS 500, INS 503), Salt, Emulsifier (INS 322)',
    sugar_100g: 33.0,
    salt_100g: 0.4,
    saturated_fat_100g: 14.0,
    image_url: null,
  },

  // ── Instant Noodles ──
  {
    barcode: '8901058811001',
    name: 'Maggi 2-Minute Masala Noodles',
    brand: 'Nestle',
    category: 'instant_noodles',
    ingredients_text: 'Wheat Flour (Maida), Palm Oil, Salt, Wheat Gluten, Thickeners (INS 412, INS 508), Acidity Regulators (INS 501, INS 500, INS 451, INS 452), Humectant (INS 451), Mineral (Iron), Colour (INS 150d), Flavour Enhancers (INS 627, INS 631), Onion Powder, Spices, Sugar, Garlic Powder',
    sugar_100g: 2.0,
    salt_100g: 2.8,
    saturated_fat_100g: 7.0,
    image_url: null,
  },
  {
    barcode: '8901058811018',
    name: 'Maggi Masala Noodles (Pack of 4)',
    brand: 'Nestle',
    category: 'instant_noodles',
    ingredients_text: 'Wheat Flour (Maida), Palm Oil, Salt, Wheat Gluten, Thickeners (INS 412, INS 508), Acidity Regulators (INS 501, INS 500, INS 451, INS 452), Flavour Enhancers (INS 627, INS 631), Onion Powder, Spices, Sugar, Garlic Powder, Colour (INS 150d)',
    sugar_100g: 2.0,
    salt_100g: 2.8,
    saturated_fat_100g: 7.0,
    image_url: null,
  },
  {
    barcode: '8904004400286',
    name: 'Yippee Noodles Magic Masala',
    brand: 'ITC Sunfeast',
    category: 'instant_noodles',
    ingredients_text: 'Wheat Flour (Maida), Edible Vegetable Oil (Palm Oil), Salt, Wheat Gluten, Mineral (Iron), Thickener (INS 412), Acidity Regulators (INS 501, INS 500), Colour (INS 150d), Spice Mix, Onion Powder, Garlic Powder, Flavour Enhancers (INS 627, INS 631), Sugar',
    sugar_100g: 2.5,
    salt_100g: 2.5,
    saturated_fat_100g: 6.5,
    image_url: null,
  },
  {
    barcode: '8901725181567',
    name: 'Top Ramen Curry Noodles',
    brand: 'Nissin',
    category: 'instant_noodles',
    ingredients_text: 'Wheat Flour (Maida), Edible Vegetable Oil (Palm Oil), Salt, Thickener (INS 412), Acidity Regulators (INS 501, INS 500), Wheat Gluten, Spices, Curry Powder, Flavour Enhancers (INS 621, INS 627, INS 631), Onion Powder, Sugar, Colour (INS 150d)',
    sugar_100g: 3.0,
    salt_100g: 3.0,
    saturated_fat_100g: 7.5,
    image_url: null,
  },

  // ── Dairy ──
  {
    barcode: '8901262150019',
    name: 'Amul Butter (Pasteurized)',
    brand: 'Amul',
    category: 'dairy',
    ingredients_text: 'Milk Fat, Water, Salt, Common Salt',
    sugar_100g: 0.1,
    salt_100g: 1.5,
    saturated_fat_100g: 51.0,
    image_url: null,
  },
  {
    barcode: '8901262011044',
    name: 'Amul Taaza Toned Milk',
    brand: 'Amul',
    category: 'dairy',
    ingredients_text: 'Toned Milk',
    sugar_100g: 4.7,
    salt_100g: 0.1,
    saturated_fat_100g: 1.9,
    image_url: null,
  },
  {
    barcode: '8901262160025',
    name: 'Amul Processed Cheese',
    brand: 'Amul',
    category: 'dairy',
    ingredients_text: 'Cheese, Water, Milk Solids, Emulsifying Salts (INS 452, INS 339), Common Salt, Acidity Regulator (INS 330), Preservative (INS 200), Annatto Colour (INS 160b)',
    sugar_100g: 2.0,
    salt_100g: 3.0,
    saturated_fat_100g: 17.0,
    image_url: null,
  },
  {
    barcode: '8901030544606',
    name: 'Amul Kool Chocolate Milk',
    brand: 'Amul',
    category: 'dairy',
    ingredients_text: 'Milk, Sugar, Cocoa Powder, Stabilizer (INS 407), Flavour',
    sugar_100g: 12.0,
    salt_100g: 0.2,
    saturated_fat_100g: 2.5,
    image_url: null,
  },
  {
    barcode: '8901262250016',
    name: 'Amul Masti Dahi (Curd)',
    brand: 'Amul',
    category: 'dairy',
    ingredients_text: 'Pasteurised Toned Milk, Bacterial Culture',
    sugar_100g: 4.5,
    salt_100g: 0.1,
    saturated_fat_100g: 1.8,
    image_url: null,
  },
  {
    barcode: '8906002560318',
    name: 'Mother Dairy Classic Curd',
    brand: 'Mother Dairy',
    category: 'dairy',
    ingredients_text: 'Pasteurised Toned Milk, Live Active Cultures',
    sugar_100g: 4.5,
    salt_100g: 0.1,
    saturated_fat_100g: 1.7,
    image_url: null,
  },

  // ── Beverages ──
  {
    barcode: '8901764010108',
    name: 'Frooti Mango Drink',
    brand: 'Parle Agro',
    category: 'beverages',
    ingredients_text: 'Water, Sugar, Mango Pulp, Citric Acid (INS 330), Mango Flavour, Preservative (INS 211), Antioxidant (INS 300), Colour (INS 110)',
    sugar_100g: 13.0,
    salt_100g: 0.0,
    saturated_fat_100g: 0.0,
    image_url: null,
  },
  {
    barcode: '8901764011006',
    name: 'Maaza Mango Drink',
    brand: 'Coca-Cola',
    category: 'beverages',
    ingredients_text: 'Water, Sugar, Mango Pulp (15%), Acidity Regulator (INS 330), Preservative (INS 211), Antioxidant (INS 300), Stabilizer (INS 440)',
    sugar_100g: 14.0,
    salt_100g: 0.0,
    saturated_fat_100g: 0.0,
    image_url: null,
  },
  {
    barcode: '8901396312505',
    name: 'Thums Up',
    brand: 'Coca-Cola',
    category: 'beverages',
    ingredients_text: 'Carbonated Water, Sugar, Acidity Regulator (INS 338), Caffeine, Colour (INS 150d), Flavour',
    sugar_100g: 10.6,
    salt_100g: 0.0,
    saturated_fat_100g: 0.0,
    image_url: null,
  },
  {
    barcode: '8901396325000',
    name: 'Coca-Cola',
    brand: 'Coca-Cola',
    category: 'beverages',
    ingredients_text: 'Carbonated Water, Sugar, Acidity Regulator (INS 338), Caffeine, Colour (INS 150d), Natural Flavouring Substances',
    sugar_100g: 10.6,
    salt_100g: 0.0,
    saturated_fat_100g: 0.0,
    image_url: null,
  },
  {
    barcode: '8901396310006',
    name: 'Sprite',
    brand: 'Coca-Cola',
    category: 'beverages',
    ingredients_text: 'Carbonated Water, Sugar, Acidity Regulator (INS 330), Flavour',
    sugar_100g: 9.0,
    salt_100g: 0.0,
    saturated_fat_100g: 0.0,
    image_url: null,
  },
  {
    barcode: '8901588001525',
    name: 'Pepsi',
    brand: 'PepsiCo',
    category: 'beverages',
    ingredients_text: 'Carbonated Water, Sugar, Acidity Regulator (INS 338), Caffeine, Colour (INS 150d), Flavour',
    sugar_100g: 10.8,
    salt_100g: 0.0,
    saturated_fat_100g: 0.0,
    image_url: null,
  },
  {
    barcode: '8901588002027',
    name: 'Mountain Dew',
    brand: 'PepsiCo',
    category: 'beverages',
    ingredients_text: 'Carbonated Water, Sugar, Acidity Regulators (INS 330, INS 331), Caffeine, Colour (INS 110), Antioxidant (INS 321), Flavour',
    sugar_100g: 12.0,
    salt_100g: 0.0,
    saturated_fat_100g: 0.0,
    image_url: null,
  },
  {
    barcode: '8901030721700',
    name: 'Bournvita Health Drink',
    brand: 'Cadbury',
    category: 'beverages',
    ingredients_text: 'Sugar, Cocoa Solids, Malt Extract, Milk Solids, Raising Agent (INS 500), Emulsifier (INS 322), Vitamins, Minerals, Salt, Flavour',
    sugar_100g: 37.0,
    salt_100g: 0.5,
    saturated_fat_100g: 1.5,
    image_url: null,
  },

  // ── Chips & Namkeen ──
  {
    barcode: '8901491100632',
    name: 'Lay\'s Classic Salted Chips',
    brand: 'PepsiCo',
    category: 'chips',
    ingredients_text: 'Potato, Edible Vegetable Oil (Palm Oil, Rice Bran Oil), Salt, Sugar, Seasoning (Maltodextrin, Salt, Acidity Regulator INS 330, Flavour Enhancer INS 635)',
    sugar_100g: 1.0,
    salt_100g: 1.5,
    saturated_fat_100g: 10.0,
    image_url: null,
  },
  {
    barcode: '8901491100649',
    name: 'Lay\'s Magic Masala Chips',
    brand: 'PepsiCo',
    category: 'chips',
    ingredients_text: 'Potato, Edible Vegetable Oil (Palm Oil, Rice Bran Oil), Seasoning (Sugar, Salt, Spices, Maltodextrin, Acidity Regulators INS 330 INS 334, Onion Powder, Garlic Powder, Flavour Enhancer INS 635, Tomato Powder, Colour INS 110)',
    sugar_100g: 3.0,
    salt_100g: 1.8,
    saturated_fat_100g: 10.0,
    image_url: null,
  },
  {
    barcode: '8901491502474',
    name: 'Kurkure Masala Munch',
    brand: 'PepsiCo',
    category: 'chips',
    ingredients_text: 'Rice Meal, Edible Vegetable Oil (Palm Oil), Corn Meal, Gram Meal, Spices, Salt, Sugar, Dried Onion, Tartaric Acid (INS 334), Milk Solids, Citric Acid (INS 330), Flavour Enhancer (INS 635)',
    sugar_100g: 3.0,
    salt_100g: 2.0,
    saturated_fat_100g: 11.0,
    image_url: null,
  },
  {
    barcode: '8901063060104',
    name: 'Haldiram\'s Aloo Bhujia',
    brand: 'Haldiram\'s',
    category: 'namkeen',
    ingredients_text: 'Potato, Gram Flour (Besan), Edible Vegetable Oil (Palm Oil), Rice Flour, Salt, Spices (Red Chilli Powder, Turmeric, Cumin, Coriander), Black Salt, Acidity Regulator (INS 330), Antioxidant (INS 319)',
    sugar_100g: 2.0,
    salt_100g: 2.5,
    saturated_fat_100g: 12.0,
    image_url: null,
  },
  {
    barcode: '8901063060111',
    name: 'Haldiram\'s Moong Dal',
    brand: 'Haldiram\'s',
    category: 'namkeen',
    ingredients_text: 'Moong Dal, Edible Vegetable Oil (Palm Oil), Salt, Black Salt, Spices (Cumin, Black Pepper, Red Chilli), Asafoetida (Hing), Antioxidant (INS 319)',
    sugar_100g: 1.0,
    salt_100g: 2.2,
    saturated_fat_100g: 10.0,
    image_url: null,
  },
  {
    barcode: '8901063060128',
    name: 'Haldiram\'s Bhujia Sev',
    brand: 'Haldiram\'s',
    category: 'namkeen',
    ingredients_text: 'Gram Flour (Besan), Edible Vegetable Oil (Palm Oil), Black Pepper, Salt, Red Chilli, Spices, Asafoetida (Hing), Antioxidant (INS 319)',
    sugar_100g: 1.5,
    salt_100g: 2.5,
    saturated_fat_100g: 13.0,
    image_url: null,
  },
  {
    barcode: '8901491501934',
    name: 'Uncle Chipps Spicy Treat',
    brand: 'PepsiCo',
    category: 'chips',
    ingredients_text: 'Potato, Edible Vegetable Oil (Palm Oil, Rice Bran Oil), Seasoning (Spices, Salt, Sugar, Maltodextrin, Onion Powder, Tomato Powder, Garlic Powder, Acidity Regulators INS 330 INS 334, Flavour Enhancer INS 635)',
    sugar_100g: 2.5,
    salt_100g: 1.8,
    saturated_fat_100g: 10.0,
    image_url: null,
  },

  // ── Chocolates & Sweets ──
  {
    barcode: '8901233020419',
    name: 'Cadbury Dairy Milk Chocolate',
    brand: 'Cadbury',
    category: 'chocolate',
    ingredients_text: 'Sugar, Cocoa Butter, Milk Solids, Cocoa Solids, Emulsifiers (INS 442, INS 476), Flavour',
    sugar_100g: 56.0,
    salt_100g: 0.3,
    saturated_fat_100g: 19.0,
    image_url: null,
  },
  {
    barcode: '8901233024547',
    name: 'Cadbury 5 Star',
    brand: 'Cadbury',
    category: 'chocolate',
    ingredients_text: 'Sugar, Glucose Syrup, Hydrogenated Vegetable Oil, Milk Solids, Cocoa Solids, Wheat Flour, Emulsifiers (INS 322, INS 471), Salt, Flavour',
    sugar_100g: 50.0,
    salt_100g: 0.4,
    saturated_fat_100g: 15.0,
    image_url: null,
  },
  {
    barcode: '87157727',
    name: 'KitKat',
    brand: 'Nestle',
    category: 'chocolate',
    ingredients_text: 'Sugar, Wheat Flour (Maida), Cocoa Butter, Milk Solids, Cocoa Mass, Vegetable Fat (Palm Oil), Emulsifier (INS 322), Yeast, Salt, Raising Agent (INS 500), Flavour',
    sugar_100g: 48.0,
    salt_100g: 0.3,
    saturated_fat_100g: 16.0,
    image_url: null,
  },

  // ── Sauces & Condiments ──
  {
    barcode: '8901058811100',
    name: 'Maggi Hot & Sweet Tomato Chilli Sauce',
    brand: 'Nestle',
    category: 'sauces',
    ingredients_text: 'Tomato Paste, Sugar, Water, Red Chilli, Salt, Acetic Acid (INS 260), Thickener (INS 415), Onion, Garlic, Ginger, Spices, Acidity Regulator (INS 330), Preservative (INS 211)',
    sugar_100g: 28.0,
    salt_100g: 3.0,
    saturated_fat_100g: 0.1,
    image_url: null,
  },
  {
    barcode: '8901058002003',
    name: 'Kissan Mixed Fruit Jam',
    brand: 'Kissan (HUL)',
    category: 'spreads',
    ingredients_text: 'Sugar, Mixed Fruit Pulp (Pineapple, Apple, Papaya, Grapes), Water, Acidity Regulator (INS 330), Gelling Agent (INS 440), Preservative (INS 211), Colour (INS 129)',
    sugar_100g: 62.0,
    salt_100g: 0.1,
    saturated_fat_100g: 0.0,
    image_url: null,
  },
  {
    barcode: '8901058848007',
    name: 'Maggi Masala-ae-Magic',
    brand: 'Nestle',
    category: 'spices',
    ingredients_text: 'Salt, Rice Flour, Coriander, Onion, Red Chilli, Turmeric, Cumin, Black Pepper, Ginger, Garlic, Fenugreek, Clove, Cardamom, Cinnamon, Flavour Enhancer (INS 621), Anti-Caking Agent (INS 551)',
    sugar_100g: 1.0,
    salt_100g: 38.0,
    saturated_fat_100g: 0.5,
    image_url: null,
  },

  // ── Spices & Masala ──
  {
    barcode: '8901072002009',
    name: 'MDH Chana Masala',
    brand: 'MDH',
    category: 'spices',
    ingredients_text: 'Coriander, Red Chilli, Salt, Cumin, Turmeric, Dry Mango Powder (Amchoor), Black Pepper, Dry Ginger, Fenugreek, Asafoetida (Hing), Clove, Cinnamon, Cardamom, Bay Leaf, Black Salt',
    sugar_100g: 2.0,
    salt_100g: 8.0,
    saturated_fat_100g: 1.0,
    image_url: null,
  },
  {
    barcode: '8901072001009',
    name: 'MDH Garam Masala',
    brand: 'MDH',
    category: 'spices',
    ingredients_text: 'Coriander, Cumin, Black Pepper, Cardamom, Clove, Cinnamon, Bay Leaf, Fennel, Nutmeg, Mace',
    sugar_100g: 1.0,
    salt_100g: 0.5,
    saturated_fat_100g: 1.5,
    image_url: null,
  },
  {
    barcode: '8901042400303',
    name: 'Everest Kitchen King Masala',
    brand: 'Everest',
    category: 'spices',
    ingredients_text: 'Coriander, Red Chilli, Salt, Cumin, Turmeric, Black Pepper, Ginger, Fenugreek Seeds, Cardamom, Clove, Cinnamon, Nutmeg, Mace, Bay Leaf',
    sugar_100g: 2.0,
    salt_100g: 6.0,
    saturated_fat_100g: 1.0,
    image_url: null,
  },

  // ── Breakfast & Cereals ──
  {
    barcode: '8901399222368',
    name: 'Kellogg\'s Chocos',
    brand: 'Kellogg\'s',
    category: 'cereals',
    ingredients_text: 'Wheat Flour, Sugar, Cocoa Solids, Edible Vegetable Oil (Palm Oil), Malt Extract, Salt, Minerals, Vitamins, Emulsifier (INS 322), Colour (INS 150d), Antioxidant (INS 320)',
    sugar_100g: 32.0,
    salt_100g: 0.6,
    saturated_fat_100g: 3.0,
    image_url: null,
  },
  {
    barcode: '8901399222283',
    name: 'Kellogg\'s Corn Flakes Original',
    brand: 'Kellogg\'s',
    category: 'cereals',
    ingredients_text: 'Corn, Sugar, Malt Flavouring, Salt, Iron, Vitamins (Niacin, B6, B2, B1, Folic Acid, B12), Antioxidant (INS 320)',
    sugar_100g: 8.0,
    salt_100g: 1.1,
    saturated_fat_100g: 0.1,
    image_url: null,
  },

  // ── Oil & Cooking ──
  {
    barcode: '8901058002133',
    name: 'Fortune Sunflower Oil',
    brand: 'Adani Wilmar',
    category: 'cooking_oil',
    ingredients_text: 'Refined Sunflower Oil, Antioxidant (INS 319)',
    sugar_100g: 0.0,
    salt_100g: 0.0,
    saturated_fat_100g: 11.0,
    image_url: null,
  },
  {
    barcode: '8901058853001',
    name: 'Saffola Gold Oil',
    brand: 'Marico',
    category: 'cooking_oil',
    ingredients_text: 'Refined Rice Bran Oil, Refined Safflower Oil, Antioxidant (INS 319)',
    sugar_100g: 0.0,
    salt_100g: 0.0,
    saturated_fat_100g: 9.0,
    image_url: null,
  },

  // ── Bread & Bakery ──
  {
    barcode: '8901063010123',
    name: 'Britannia Whole Wheat Bread',
    brand: 'Britannia',
    category: 'bread',
    ingredients_text: 'Whole Wheat Flour (Atta), Water, Sugar, Yeast, Edible Vegetable Oil (Palm Oil), Wheat Gluten, Iodised Salt, Preservative (INS 282), Emulsifier (INS 481), Flour Treatment Agent (INS 300)',
    sugar_100g: 5.0,
    salt_100g: 1.0,
    saturated_fat_100g: 1.5,
    image_url: null,
  },

  // ── Tea & Coffee ──
  {
    barcode: '8901030711000',
    name: 'Nescafe Classic Instant Coffee',
    brand: 'Nestle',
    category: 'beverages',
    ingredients_text: 'Instant Coffee (100% Coffee)',
    sugar_100g: 0.0,
    salt_100g: 0.0,
    saturated_fat_100g: 0.0,
    image_url: null,
  },

  // ── More Snacks ──
  {
    barcode: '8901725181574',
    name: 'Bingo Mad Angles Achaari Masti',
    brand: 'ITC',
    category: 'chips',
    ingredients_text: 'Corn Meal, Edible Vegetable Oil (Palm Oil), Rice Meal, Gram Meal, Seasoning (Spices, Salt, Sugar, Dried Mango, Acidity Regulator INS 330, Onion Powder, Flavour Enhancer INS 635, Maltodextrin)',
    sugar_100g: 3.0,
    salt_100g: 2.0,
    saturated_fat_100g: 11.0,
    image_url: null,
  },
  {
    barcode: '8901491504362',
    name: 'Doritos Sweet Chilli',
    brand: 'PepsiCo',
    category: 'chips',
    ingredients_text: 'Corn, Edible Vegetable Oil (Palm Oil), Seasoning (Sugar, Salt, Spices, Maltodextrin, Tomato Powder, Onion Powder, Garlic Powder, Acidity Regulators INS 330 INS 270, Flavour Enhancer INS 635, Colour INS 110 INS 124)',
    sugar_100g: 5.0,
    salt_100g: 1.5,
    saturated_fat_100g: 9.0,
    image_url: null,
  },
];

export default seedProducts;
